defaults: &defaults
  MQTT_HOST: localhost
  MQTT_PORT: 1883
  MQTT_TLS: false
  IF_ADDR: 
  # 设备上报消息速率，单位：条/秒
  MESSAGE_RATE: 10
  # 消息上报持续时间，单位：秒
  MESSAGE_DURATION: 100_000

  DEVICE_STEP_NUM: 500
  DEVICE_NUM: 2000
  DEVICE_TRIAD_FILEPATH: ./configs/local_triads_zh.txt
  COMM_FILEPATH: ./configs/mocker_msg.json

development: &development
  <<: *defaults
  MQTT_HOST: pre-mqtt.fogcloud.io
  MQTT_PORT: 8883
  MQTT_TLS: true

  DEVICE_STEP_NUM: 100
  DEVICE_NUM: 500
  DEVICE_TRIAD_FILEPATH: ./configs/prod_triads.txt

test:
  <<: *development
  MESSAGE_RATE: 0
  DEVICE_TRIAD_FILEPATH: /Users/lethe/code/work/thingmocker/configs/prod_triads.txt
  COMM_FILEPATH: /Users/lethe/code/work/thingmocker/configs/mocker_msg.json